[#24] 호스트가 숙소 등록을 할 수 있다
prgrms-be-devcourse/BEDV2_Amabnb pull request #31
Opened 2022-06-22 02:39 UTC by yongsu-kang

## 작업사항
- room 엔티티 작성 및 수정
- createDto 생성
- repo, service, api 구현 및 테스트 코드 작성

resolves #24

2022-06-22 04:55 UTC, yuminhwan requested changes
수고하셨습니다!! 🎉
몇가지 코멘트 남겼습니다!

2022-06-22 04:55 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/api/RoomApiController.java
> +    public ResponseEntity createRoom(@Valid @RequestBody CreateRoomRequest createRoomRequest) {
```suggestion
    public ResponseEntity<Void> createRoom(@Valid @RequestBody CreateRoomRequest createRoomRequest) {
```
로우 타입은 피하는 게 좋아보입니다!

2022-06-22 04:55 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/api/RoomApiController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
```suggestion
        return ResponseEntity.created(uri).build();
```
생성된 자원에 대한 Location을 넣어주면 좋을 것 같아요!

2022-06-22 04:55 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/entity/dto/request/CreateRoomRequest.java
> +    private int bathRoomCnt;
모두 0이면 문제가 되지 않을까요??

2022-06-22 04:55 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/entity/dto/request/CreateRoomRequest.java
> +    public static Room toRoom(CreateRoomRequest request) {
```suggestion
    public Room toRoom() {
```
request를 다시 받아서 클래스 메서드로 처리하는 것 보단 인스턴스 메서드로 처리하는 것이 좋아보입니다!

2022-06-22 04:55 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/entity/vo/RoomOption.java
> +    }
여기도 다 0이면 문제가 되지 않을까요?

2022-06-22 04:55 UTC, yuminhwan commented on src/test/java/com/prgrms/amabnb/room/service/CreateRoomServiceTest.java
> +
RoomRepository는 주입을 안시켜주나요?? 🤔

2022-06-22 04:55 UTC, yuminhwan commented on src/test/java/com/prgrms/amabnb/room/api/RoomApiControllerTest.java
> +}
사소한 거지만 POSIX 표준이라고 하더라구요!!
`Ensure every saved file ends with a line break` 인텔리제이에서 검색해서 적용하면 좋을 것 같습니다!

2022-06-22 06:19 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/room/api/RoomApiController.java
> +    public ResponseEntity createRoom(@Valid @RequestBody CreateRoomRequest createRoomRequest) {
넵!!!!

2022-06-22 06:21 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/room/entity/dto/request/CreateRoomRequest.java
> +    private int bathRoomCnt;
등록할 때 0인 부분이 있어서 0으로 등록을 해도 된다고 생각했습니다.
침대 수 경우에는 대한민국 특성상 마루바닥에도 잘 수 있다?? 생각했습니닿 ㅎㅎ

2022-06-22 06:21 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/room/entity/dto/request/CreateRoomRequest.java
> +    public static Room toRoom(CreateRoomRequest request) {
넵 수정하도록 하고 메소드 이름도 toEntity로 변경하겠습니다~

2022-06-22 06:23 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/room/api/RoomApiController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
넵!!!

2022-06-22 06:31 UTC, yongsu-kang commented on src/test/java/com/prgrms/amabnb/room/service/CreateRoomServiceTest.java
> +
아하!!! ㅎㅎㅎㅎㅎ

2022-06-22 07:20 UTC, yongsu-kang commented
api 테스트 도중에 jwtTokenProvider에서 에러가나서 테스트 코드를 완전히 갈아없진 못했습니다.

2022-06-22 09:53 UTC, yuminhwan approved these changes
꼼꼼한 검증 좋네요!! 🎉

2022-06-22 09:53 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/dto/request/CreateRoomRequest.java
> +    @PositiveOrZero
Contorller 어드바이스에 validation 관련 메서드 만들어 두면 좋을 것 같습니다! 
Enum 매핑도요!!

2022-06-22 09:53 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/entity/Room.java
> +            throw new IllegalArgumentException("최대 인원 수 입력값이 잘못됐습니다");
커스텀 예외로 바꾸면 좋을 것 같아요!!

2022-06-22 09:53 UTC, yuminhwan commented on src/test/java/com/prgrms/amabnb/room/api/RoomApiControllerTest.java
> +class RoomApiControllerTest {
시큐리티 적용된 테스트의 경우 이 글 참고하시면 좋을 것 같습니다!!
- [Spring Security가 적용된 곳을 효율적으로 테스트하자.](https://tecoble.techcourse.co.kr/post/2020-09-30-spring-security-test/)

2022-06-22 09:53 UTC, yuminhwan commented on src/test/java/com/prgrms/amabnb/room/service/CreateRoomServiceTest.java
> +                .build();
이것도 메서드로 빼면 보기 좋을 것 같아요! 
- [테스트 픽스처 올바르게 사용하기](https://jojoldu.tistory.com/611?category=1036934)

2022-06-22 14:43 UTC, 78planet approved these changes

2022-06-23 05:00 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/room/entity/Room.java
> +            throw new IllegalArgumentException("최대 인원 수 입력값이 잘못됐습니다");
변경하도록 할게요~~

2022-06-23 05:02 UTC, yongsu-kang commented on src/test/java/com/prgrms/amabnb/room/api/RoomApiControllerTest.java
> +class RoomApiControllerTest {
@WthMockUser 와 with(SecurityMockMvcRequestPostProcessors.csrf()) 으로 security 로그인 적용되는 부분을 해결할 수 있었습니다!!

2022-06-23 05:21 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/room/dto/request/CreateRoomRequest.java
> +    @PositiveOrZero
추가!!

2022-06-23 05:48 UTC, kimziou77 approved these changes
확인했습니다! 어서 시큐리티랑 통합해서 돌려봐야겠네요 😃

2022-06-23 05:53 UTC, yuminhwan approved these changes
컨벤션 확인 한번만 부탁드립니다!

2022-06-23 05:53 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/common/exception/GlobalExceptionHandler.java
> +                .body(new ErrorResponse("서버에서 에러가 발생했습니다."));
혹시 컨벤션 파일 적용하신건가요??
아님 임의로 바꾸신건가요??

2022-06-23 05:53 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/common/exception/GlobalExceptionHandler.java
> +                .body(new ErrorResponse("Validation 에러가 발생했습니다."));
상세 예외로 바꾸시면 좋을 것 같은데 제가 나중에 리팩토링하겠습니다~!

2022-06-23 06:24 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/common/exception/GlobalExceptionHandler.java
> +                .body(new ErrorResponse("서버에서 에러가 발생했습니다."));
임의로 바꾼건 아닌데 저렇게 되어 있더라고요???

2022-06-23 06:54 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/common/exception/GlobalExceptionHandler.java
> +                .body(new ErrorResponse("서버에서 에러가 발생했습니다."));
컨벤션 파일 적용이 안되있었네요 ㅎㅎ

2022-06-23 07:03 UTC, merged