[#25] 로컬에 이미지 업로드 API 추가
prgrms-be-devcourse/BEDV2_Amabnb pull request #36
Opened 2022-06-23 09:50 UTC by 78planet

## 작업사항
로컬에 이미지 업로드하는 API 추가하였습니다. 
POST /room-images

resolves #25

2022-06-24 02:39 UTC, yongsu-kang reviewed
대단히 고생하셨습니다!!!

2022-06-24 02:39 UTC, yongsu-kang commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +            }
service 레이어에서 처리하면 좋지 않을 까 생각합니다!

2022-06-24 06:50 UTC, yuminhwan requested changes
재욱님 수고많으셨습니다! 
몇가지 코멘트 남겼는데 확인해주세요!!

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/AmabnbApplication.java
> +@SpringBootApplication(exclude = { SecurityAutoConfiguration.class })
테스트 때문에 작성하신 것 같은데 PR올리실 땐 빼주셔야 할 것 같습니다!

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +    String dirPath = "/Users/willkim/IdeaProjects/BEDV2_Amabnb/src/main/resources/images";
이 경로가 없다면 예외가 발생하지 않을까요? 차라리 classpath로 지정해도 좋을 것 같습니다.

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +        }
커스텀 예외로 보내면 좋을 것 같습니다!

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +                String imageName = userId + "-" + randomUUID + "-" + file.getOriginalFilename() + "-" + cnt;
파일명을 이렇게 구성한 이유가 무엇인가요?

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/entity/Image.java
> +    }
필드가 두개라서 굳이 빌더가 필요없을 것 같습니다!

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/service/ImageService.java
> +    @Transactional
클래스에 `@Transactional(readOnly = true)` 있기 때문에 삭제하는 게 좋을 것 같습니다!
이런식으로 하면 아마 `@Transactional`가 적용될 겁니다.

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/entity/Room.java
> +
인텔리제이에서 final 체크 없애는 게 좋을 것 같습니다! 
원래대로 복구 부탁드려요~!

2022-06-24 06:50 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/room/entity/Room.java
> +    }
로직상 필요한 코드일까요...?
테스트용인것같은데 제거해도 좋을 것 같아요!

2022-06-24 06:50 UTC, yuminhwan commented on src/main/resources/application.yaml
> +    expire-length:
yaml파일 포맷팅 적용이 된 것 같은데 변한 거 없으면 원래대로 복구해주시면 좋을 것 같아요!

2022-06-27 05:23 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +            }
넵!

2022-06-27 05:23 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/AmabnbApplication.java
> +@SpringBootApplication(exclude = { SecurityAutoConfiguration.class })
넵!

2022-06-27 05:24 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +    String dirPath = "/Users/willkim/IdeaProjects/BEDV2_Amabnb/src/main/resources/images";
수정본에서는 경로 제외하였습니다.

2022-06-27 05:24 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +        }
커스텀 예외! 넵

2022-06-27 05:26 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +                String imageName = userId + "-" + randomUUID + "-" + file.getOriginalFilename() + "-" + cnt;
수정본에서는 **UUID.randomID + file 등록 순서 숫자** 로 구성하였습니다. 
이미지 이름 중복되지 않게  랜덤하게 이름을 생성하고, 프론트에서 이미지 등록 순서대로 이미지를 보여줄 수도 있기 때문에 이미지 등록 순서도 파일명에 추가해 주었습니다.

2022-06-27 05:26 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/entity/Image.java
> +    }
넵!

2022-06-27 05:27 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/service/ImageService.java
> +    @Transactional
감사합니다!

2022-06-27 05:27 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/room/entity/Room.java
> +
넵!

2022-06-27 05:27 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/room/entity/Room.java
> +    }
넵!

2022-06-27 05:27 UTC, 78planet commented on src/main/resources/application.yaml
> +    expire-length:
넵!

2022-06-28 06:21 UTC, yuminhwan approved these changes
재욱님 수고많으셨습니다!

2022-06-28 06:21 UTC, yuminhwan commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +public class ImageUploadToS3Test {
Rest Docs 적용해주면 좋을 것 같아요!

2022-06-28 06:21 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/common/infra/s3/AWSS3Uploader.java
> +@Service
Service 레이어 인만큼 `ImageService` 라는 클래스명으로 image 패키지 밑으로 들어가도 될 것 같은데 어떻게 생각하시나요?

2022-06-28 06:23 UTC, 78planet commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +public class ImageUploadToS3Test {
넵!

2022-06-28 06:23 UTC, kimziou77 reviewed
수고하셨습니다 재욱님~ 리뷰 확인해주세요!

2022-06-28 06:23 UTC, kimziou77 commented on src/main/java/com/prgrms/amabnb/common/infra/s3/AWSS3Uploader.java
> +            fileSequence++;
IOException이 아닌 다른 이유로 실패하게 되면 fileSequence가 올라가겠네요
try 안쪽 add 뒤쪽으로 fileSequence가 들어가는 것이 좀 더 자연스러워 보입니다~

2022-06-28 06:23 UTC, kimziou77 commented on src/main/resources/application.yaml
> +      auto: false
이부분도 profiles로 빼면 좋을 것 같아요~!

2022-06-28 06:23 UTC, kimziou77 commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +                .andExpect(status().isOk());
추가 검증은 없나요?

2022-06-28 06:23 UTC, kimziou77 commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +                fileResource.getInputStream());
해당 파일은 재욱님 로컬에만 존재하는 파일이라 다른 분들 테스트에선 깨질것 같아요~!

2022-06-28 06:23 UTC, kimziou77 commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +        void 성공() throws Exception {
실패에 대한 테스트는 없을까요?

2022-06-28 06:32 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/common/infra/s3/AWSS3Uploader.java
> +@Service
AWS 자원을 사용하는 클래스들은 infra 패키지 밑에서 관리하는게 나중에 유지보수하는데 편할 것 같습니다. 그리고 `AWSS3Uploader` 클래스는 이미지 뿐만 아니라 다른 파일을 s3에 업로드할 때도 다시 활용이 가능해 보입니다. 
그렇다면 `AWSS3Uploader` 클래스는 Service 어노테이션이 아니라 Component 어노테이션이 더 어울리겠군요.

2022-06-28 06:33 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/common/infra/s3/AWSS3Uploader.java
> +            fileSequence++;
넵 감사합니다.

2022-06-28 06:49 UTC, 78planet commented on src/main/resources/application.yaml
> +      auto: false
cloud 관련 설정 정보를 profiles로 빼면 더욱 구분하기 쉽겠네요!

2022-06-28 06:49 UTC, 78planet commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +                .andExpect(status().isOk());
추가 검증 넣도록 하겠습니다.

2022-06-28 06:50 UTC, 78planet commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +        void 성공() throws Exception {
추가하겠습니다!

2022-06-28 06:53 UTC, 78planet commented on src/test/java/com/prgrms/amabnb/image/ImageUploadToS3Test.java
> +                fileResource.getInputStream());
테스트용 이미지 파일을 git에 올려야되겠군요?

2022-06-28 15:23 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/common/infra/s3/AWSS3Uploader.java
> +@Service
그렇다면 `ImageService` 인터페이스를 만들고 AWSS3Uploader에 구현하는 쪽이 더 좋아보입니다.
그렇게 분리하게 된다면 후에 로컬 이미지 업로드 기능으로 바꿔야 할때 다른 코드의 수정없이 바꿀 수 있을 것 같습니다!

2022-06-29 06:11 UTC, kimziou77 approved these changes
재욱님 수고 많으셨습니다 😸

2022-06-29 06:11 UTC, kimziou77 commented on src/main/resources/application-cloud.yaml
> +cloud:
.gitignore 에 추가되어 있는 파일이 올라와 있네요!

2022-06-29 06:11 UTC, kimziou77 commented on src/main/resources/application.yaml
> +    include: security, cloud
👍

2022-06-29 06:18 UTC, yuminhwan approved these changes
재욱님 수고하셨습니다~! 추가로 머지할 때 aws 이슈도 같이 링크해서 닫으면 되겠네요~!

2022-06-29 06:18 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +    private final AWSS3Uploader s3Uploader;
인터페이스로 의존합시다~!

2022-06-29 06:18 UTC, yuminhwan commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +        return ResponseEntity.ok(s3Uploader.uploadImage(images, "static"));
"static"은 aws에서만 사용하는 것이니 `AWSS3Uploader` 안에 상수로 정의하거나 @Value로 받아서 사용하면 될 것 같아요!

2022-06-29 06:20 UTC, 78planet commented on src/main/resources/application.yaml
> +    include: security, cloud
application-cloud.yaml 파일은 .gitignore에 추가를 안해도 되겠네요. 감사합니다.

2022-06-29 06:30 UTC, kimziou77 commented on src/main/resources/application.yaml
> +    include: security, cloud
앗 gitignore에 추가하고, application-cloud.yaml 파일은 저희팀 로컬에만 존재하는 파일로 관리하면 좋을 것 같습니다.

2022-06-29 06:30 UTC, yongsu-kang approved these changes

2022-06-29 06:31 UTC, kimziou77 commented
안돼앵 깃이그노어를 복구해주세요 😿

2022-06-29 06:46 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +        return ResponseEntity.ok(s3Uploader.uploadImage(images, "static"));
넵!

2022-06-29 06:46 UTC, 78planet commented on src/main/java/com/prgrms/amabnb/image/api/ImageController.java
> +    private final AWSS3Uploader s3Uploader;
수정했습니다!

2022-06-29 06:53 UTC, 78planet commented
> 안돼앵 깃이그노어를 복구해주세요 😿

수빈님과 원만한 합의를 통해 gitignore에는 cloud 설정 파일을 제외하기로 했습니다.

2022-06-29 06:53 UTC, merged